- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'portainer'
        intport: '9000'
        extport: '9000'
        image: 'portainer/portainer-ce:alpine'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.http.routers.portainer.entryPoints: 'secure'
          traefik.http.routers.portainer.rule: 'Host({{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}})'
          traefik.http.routers.portainer.tls: 'true'
          traefik.http.routers.portainer.tls.certResolver: 'leresolver'
          traefik.http.routers.portainer.tls.domains: '{{domain.stdout}}'
          traefik.http.routers.portainer.middlewares: 'portainer-mw'
          traefik.http.middlewares.portainer-mw.headers.customResponseHeaders.X-Robots-Tag: 'noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.http.middlewares.portainer-mw.headers.SSLRedirect: 'true'
          traefik.http.middlewares.portainer-mw.headers.SSLHost: '{{domain.stdout}}'
          traefik.http.middlewares.portainer-mw.headers.SSLForceHost: 'true'
          traefik.http.middlewares.portainer-mw.headers.STSSeconds: '315360000'
          traefik.http.middlewares.portainer-mw.headers.STSIncludeSubdomains: 'true'
          traefik.http.middlewares.portainer-mw.headers.STSPreload: 'true'
          traefik.http.middlewares.portainer-mw.headers.forceSTSHeader: 'true'
          traefik.http.middlewares.portainer-mw.headers.frameDeny: 'true'
          traefik.http.middlewares.portainer-mw.headers.contentTypeNosniff: 'true'
          traefik.http.middlewares.portainer-mw.headers.browserXSSFilter: 'true'
          traefik.http.middlewares.portainer-mw.headers.customFrameOptionsValue: 'allow-from {{domain.stdout}}'
          traefik.http.services.portainer-svc.loadBalancer.server.port: '9000'
          traefik.http.services.portainer-svc.loadBalancer.passHostHeader: 'true'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/appdata/{{pgrole}}:/data'
          - '/var/run/docker.sock:/var/run/docker.sock'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
